# Workflow
name: Deploy website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Symfony (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: ${{ secrets.APP_DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.APP_DB_NAME }}
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit-bridge
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          coverage: xdebug

      - name: Start mysql service
        run: sudo systemctl start mysql

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass

      # - name: Make .env.local production file
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_APP_ENV: prod
      #     envkey_APP_DEBUG: false
      #     envkey_DATABASE_URL: mysql://${{ secrets.APP_DB_USER }}:${{ secrets.APP_DB_PASS }}@127.0.0.1:3306/${{ secrets.APP_DB_NAME }}?serverVersion=8.0.28
      #     file_name: .env.local

      # - name: create .env.local file
      #   run: |
      #     touch .env.local
      #     echo DATABASE_URL: mysql://${{ secrets.APP_DB_USER }}:${{ secrets.APP_DB_PASS }}@127.0.0.1:3306/${{ secrets.APP_DB_NAME }}?serverVersion=8.0.28 >> .env.local
      #     echo APP_ENV: prod >> .env.local
      #     echo APP_DEBUG: false >> .env.local

      - name: deploy
        run:
          sshpass -e ssh -p 9005 -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "
          cd www/arakis.s2ii.xyz/
          && git pull
          && composer install --no-progress --prefer-dist --optimize-autoloader
          && php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed
          && php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
          "
        env:
          DATABASE_URL: mysql://root:${{ secrets.APP_DB_PASS }}@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/${{ secrets.APP_DB_NAME }}


