# Workflow
name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass

      - name: Make .env production file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_ENV: prod
          envkey_APP_DEBUG: false
          envkey_DATABASE_URL: mysql://${{ secrets.APP_DB_USER }}:${{ secrets.APP_DB_PASS }}@127.0.0.1:3306/${{ secrets.APP_DB_NAME }}
          file_name: .env.local

      - name: deploy
        run:
          sshpass -e ssh -p 9005 -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd www/arakis.s2ii.xyz/ &&
          git pull &&
          composer install --no-progress --prefer-dist --optimize-autoloader &&
          php bin/console d:d:c &&
          php bin/console d:m:m -n"

