# Workflow
name: Deploy website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4']

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, dom, filter, intl, mysql, pdo_mysql, json, gd, cmi, curl, zip, opcache, apcu
        env:
          update: true

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass

      # - name: Make .env.local production file
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_APP_ENV: prod
      #     envkey_APP_DEBUG: false
      #     envkey_DATABASE_URL: mysql://${{ secrets.APP_DB_USER }}:${{ secrets.APP_DB_PASS }}@127.0.0.1:3306/${{ secrets.APP_DB_NAME }}?serverVersion=8.0.28
      #     file_name: .env.local

      - name: create .env.local file
        run: |
          touch .env.local
          echo DATABASE_URL: mysql://${{ secrets.APP_DB_USER }}:${{ secrets.APP_DB_PASS }}@127.0.0.1:3306/${{ secrets.APP_DB_NAME }}?serverVersion=8.0.28 >> .env.local
          echo APP_ENV: prod >> .env.local
          APP_DEBUG: false >> .env.local

      - name: deploy
        run:
          sshpass -e ssh -p 9005 -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd www/arakis.s2ii.xyz/ &&
          git pull &&
          composer install --no-progress --prefer-dist --optimize-autoloader &&
          php bin/console d:d:c &&
          php bin/console d:m:m -n"
